seed: 1
model_path: best_models
model_folders: |
  e3-6images-210523-031950
  e4-switch-6img-210524-200612
  e4-switch-6img-210524-204656
test_path: 10000games-6img-same.pkl
dataset: data/big/mcrae-wordnet-vgg16.32bit
out_name: 10000games-same.results
role_alteration: no
