seed: 1
model_path: models
model_folders: |
  e4-switch-4images-210520-043339
  e4-switch-4images-210520-044849
  e4-switch-4images-210520-050746
  e4-switch-4images-210520-052225
test_path: 5000games-4img.pkl
dataset: data/big/mcrae-wordnet-vgg16.32bit
out_name: 5000games4i.results
role_alteration: yes
