seed: 1
model_path: models
model_folders: |
  settings-reinforce-e1explore-adam-210511-191821
  settings-reinforce-e1explore-adam-210511-193317
  settings-reinforce-e1explore-adam-210511-194204
  settings-reinforce-e1explore-adam-210511-195610
  settings-reinforce-e1explore-adam-210511-200501
  settings-reinforce-e1explore-adam-210511-201641
test_path: test-games.pkl
dataset: data/big/mcrae-wordnet-vgg16.32bit
out_name: e1explore.test-2i-1k.results
