seed: 1
out_dir: models
dataset: data/big/mcrae-wordnet-vgg16.32bit
#dataset: data/small-mcrae-wordnet-vgg16.32bit
#dataset: data/imagenet-200x65-vgg19.train.emb.gz
number_of_episodes: 40000
batch_size: 30
number_of_images: 2
embedding_size: 50
vocabulary_size: 50
optimizer: adam
analysis_window: 30
early_stopping_patience: 8000
early_stopping_minimum: 20000

role_mode: static
#role_mode: switch

shared_embedding: yes

shared_experience: no

sender_type: agnostic
#sender_type: informed

algorithm: reinforce
#algorithm: qlearning

#############
# REINFORCE settings
temperature: 10

#############
# Q Learning settings
max_memory: 5000

#memory_sampling_mode: last
memory_sampling_mode: uniform
#memory_sampling_mode: linear_skew

exploration_start: 1
exploration_decay: 0.999
exploration_floor: 0.005
