seed: 1
model_path: models
model_folders: |
  settings-reinforce-e1initial-210510-160622
  settings-reinforce-e1initial-210510-161531
  settings-reinforce-e1initial-210510-162434
  settings-reinforce-e1initial-210510-163311
  settings-reinforce-e1initial-210510-164301
  settings-reinforce-e1initial-210510-165313
test_path: test-games.pkl
dataset: data/big/mcrae-wordnet-vgg16.32bit
out_name: test-2i-1k.results
