algorithm: reinforce
analysis_window: 30
batch_size: 30
dataset: data/big/mcrae-wordnet-vgg16.32bit
early_stopping_minimum: 20000
early_stopping_patience: 8000
embedding_size: 50
exploration_decay: 0.999
exploration_floor: 0.005
exploration_start: 1
max_memory: 5000
memory_sampling_mode: uniform
number_of_episodes: 40000
number_of_images: 6
optimizer: adam
out_dir: models/e4-switch-6img-210524-204656
role_mode: switch
seed: 1
sender_type: agnostic
shared_embedding: true
shared_experience: true
temperature: 100
vocabulary_size: 50
