batch_mode: sample
batch_size: 20
dataset: data/imagenet-200x65-vgg19.train.emb.gz
dropout: 0
embedding_size: 50
explore: none
gibbs_temperature: 0
load_file: 200828-113037-reinforce
loss: binary_crossentropy
memory_sampling_distribution: linear
mode: test
model_dir: models
model_type: old
n_active_images: 4
n_episodes: 15000
n_informed_filters: 40
out_activation: softmax
roles: switch
save_file: 200828-113037-reinforce
sender_type: informed
shared_embedding: true
shared_experience: false
stop_when_goal_is_passed: true
trim_dataset_to_n_images: false
use_categories: true
vocabulary_size: 10
