batch_mode: sample
batch_size: 30
dataset: data/imagenet-200x65-vgg19.train.emb.gz
dropout: 0
embedding_size: 50
explore: gibbs
gibbs_temperature: 0.1
load_file: 200818-182634-sharedexp
loss: binary_crossentropy
memory_sampling_distribution: linear
mode: test
model_dir: models
n_active_images: 4
n_episodes: 50000
n_informed_filters: 20
out_activation: softmax
roles: fixed
save_file: 200818-182634-sharedexp
sender_type: informed
shared_embedding: true
shared_experience: false
stop_when_goal_is_passed: true
trim_dataset_to_n_images: null
use_categories: true
vocabulary_size: 10
